import { Router } from "express";
import authRoutes from "./authRoutes";
import subjectRoutes from "./subjectRoutes";
import topicRoutes from "./topicRoutes";
import flashcardRoutes from "./flashcardRoutes";
import quizRoutes from "./quizRoutes";
import progressRoutes from "./progressRoutes";
import leaderboardRoutes from "./leaderboardRoutes";
import challengeRoutes from "./challengeRoutes";
import xpHistoryRoutes from "./xpHistoryRoutes";
import badgeAdminRoutes from "./admin/badgeAdminRoutes";
import achievementAdminRoutes from "./admin/achievementAdminRoutes";
import challengeAdminRoutes from "./admin/challengeAdminRoutes";
import rewardsAdminRoutes from "./admin/rewardsAdminRoutes";
import reportingAdminRoutes from "./admin/reportingAdminRoutes";
import metricsAdminRoutes from "./admin/metricsAdminRoutes";
import exportAdminRoutes from "./admin/exportAdminRoutes";
import userAdminRoutes from "./admin/userAdminRoutes";
import flashcardAdminRoutes from "./admin/flashcardAdminRoutes";
import quizAdminRoutes from "./admin/quizAdminRoutes";
import practiceTestAdminRoutes from "./admin/practiceTestAdminRoutes";
import questionBankAdminRoutes from "./admin/questionBankAdminRoutes";
import notificationAdminRoutes from "./admin/notificationAdminRoutes";
import supportAdminRoutes from "./admin/supportAdminRoutes";
import paymentAdminRoutes from "./admin/paymentAdminRoutes";
import subscriptionAdminRoutes from "./admin/subscriptionAdminRoutes";
import settingsAdminRoutes from "./admin/settingsAdminRoutes";
import gradeLevelAdminRoutes from "./admin/gradeLevelAdminRoutes";
import subjectAdminRoutes from "./admin/subjectAdminRoutes";
import topicAdminRoutes from "./admin/topicAdminRoutes";

const router = Router();

router.get("/health", (_req, res) => {
  res.json({ success: true, message: "Nunyalearn API healthy" });
});

router.use("/auth", authRoutes);
router.use("/subjects", subjectRoutes);
router.use("/topics", topicRoutes);
router.use("/flashcards", flashcardRoutes);
router.use("/quizzes", quizRoutes);
router.use("/progress", progressRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/challenges", challengeRoutes);
router.use("/xp-history", xpHistoryRoutes);
router.use("/admin/users", userAdminRoutes);
router.use("/admin/grades", gradeLevelAdminRoutes);
router.use("/admin/subjects", subjectAdminRoutes);
router.use("/admin/topics", topicAdminRoutes);
router.use("/admin/badges", badgeAdminRoutes);
router.use("/admin/achievements", achievementAdminRoutes);
router.use("/admin/challenges", challengeAdminRoutes);
router.use("/admin/rewards", rewardsAdminRoutes);
router.use("/admin/flashcards", flashcardAdminRoutes);
router.use("/admin/quizzes", quizAdminRoutes);
router.use("/admin/practice-tests", practiceTestAdminRoutes);
router.use("/admin/questionbank", questionBankAdminRoutes);
router.use("/admin/reporting", reportingAdminRoutes);
router.use("/admin/system", metricsAdminRoutes);
router.use("/admin/export", exportAdminRoutes);
router.use("/admin/notifications", notificationAdminRoutes);
router.use("/admin/support", supportAdminRoutes);
router.use("/admin/payments", paymentAdminRoutes);
router.use("/admin/subscriptions", subscriptionAdminRoutes);
router.use("/admin/settings", settingsAdminRoutes);

export default router;
