import { Router } from "express";
import authRoutes from "./authRoutes";
import subjectRoutes from "./subjectRoutes";
import topicRoutes from "./topicRoutes";
import flashcardRoutes from "./flashcardRoutes";
import quizRoutes from "./quizRoutes";
import progressRoutes from "./progressRoutes";
import leaderboardRoutes from "./leaderboardRoutes";
import challengeRoutes from "./challengeRoutes";
import xpHistoryRoutes from "./xpHistoryRoutes";
import curriculumRoutes from "./curriculumRoutes";
import badgeAdminRoutes from "./admin/badgeAdminRoutes";
import achievementAdminRoutes from "./admin/achievementAdminRoutes";
import challengeAdminRoutes from "./admin/challengeAdminRoutes";
import rewardsAdminRoutes from "./admin/rewardsAdminRoutes";
import reportingAdminRoutes from "./admin/reportingAdminRoutes";
import metricsAdminRoutes from "./admin/metricsAdminRoutes";
import exportAdminRoutes from "./admin/exportAdminRoutes";
import userAdminRoutes from "./admin/userAdminRoutes";
import flashcardAdminRoutes from "./admin/flashcardAdminRoutes";
import quizAdminRoutes from "./admin/quizAdminRoutes";
import practiceTestAdminRoutes from "./admin/practiceTestAdminRoutes";
import questionBankAdminRoutes from "./admin/questionBankAdminRoutes";
import notificationAdminRoutes from "./admin/notificationAdminRoutes";
import supportAdminRoutes from "./admin/supportAdminRoutes";
import paymentAdminRoutes from "./admin/paymentAdminRoutes";
import subscriptionAdminRoutes from "./admin/subscriptionAdminRoutes";
import settingsAdminRoutes from "./admin/settingsAdminRoutes";
import gradeLevelAdminRoutes from "./admin/gradeLevelAdminRoutes";
import subjectAdminRoutes from "./admin/subjectAdminRoutes";
import topicAdminRoutes from "./admin/topicAdminRoutes";
import adminCurriculumRoutes from "./admin/curriculumRoutes";
import quizV2Routes from "./v2/quizV2Routes";
import practiceTestV2Routes from "./v2/practiceTestV2Routes";
import attemptV2Routes from "./v2/attemptV2Routes";
import { adminResponseEnvelope } from "../middlewares/adminResponseEnvelope";
import { verifyToken } from "../middlewares/verifyToken";

const router = Router();

router.get("/health", (_req, res) => {
  res.json({ success: true, message: "Nunyalearn API healthy" });
});

router.use("/auth", authRoutes);
router.use("/subjects", subjectRoutes);
router.use("/topics", topicRoutes);
router.use("/flashcards", flashcardRoutes);
router.use("/quizzes", quizRoutes);
router.use("/progress", progressRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/challenges", challengeRoutes);
router.use("/xp-history", xpHistoryRoutes);
router.use("/curriculum", curriculumRoutes);
router.use("/api/v2/quizzes", verifyToken, quizV2Routes);
router.use("/api/v2/practice-tests", verifyToken, practiceTestV2Routes);
router.use("/api/v2/attempts", verifyToken, attemptV2Routes);
router.use("/admin/users", adminResponseEnvelope, userAdminRoutes);
router.use("/admin/grades", adminResponseEnvelope, gradeLevelAdminRoutes);
router.use("/admin/subjects", adminResponseEnvelope, subjectAdminRoutes);
router.use("/admin/topics", adminResponseEnvelope, topicAdminRoutes);
router.use("/admin/curriculum", adminResponseEnvelope, adminCurriculumRoutes);
router.use("/admin/badges", adminResponseEnvelope, badgeAdminRoutes);
router.use("/admin/achievements", adminResponseEnvelope, achievementAdminRoutes);
router.use("/admin/challenges", adminResponseEnvelope, challengeAdminRoutes);
router.use("/admin/rewards", adminResponseEnvelope, rewardsAdminRoutes);
router.use("/admin/flashcards", adminResponseEnvelope, flashcardAdminRoutes);
router.use("/admin/quizzes", adminResponseEnvelope, quizAdminRoutes);
router.use("/admin/practice-tests", adminResponseEnvelope, practiceTestAdminRoutes);
router.use("/admin/questionbank", adminResponseEnvelope, questionBankAdminRoutes);
router.use("/admin/reporting", adminResponseEnvelope, reportingAdminRoutes);
router.use("/admin/system", adminResponseEnvelope, metricsAdminRoutes);
router.use("/admin/export", adminResponseEnvelope, exportAdminRoutes);
router.use("/admin/notifications", adminResponseEnvelope, notificationAdminRoutes);
router.use("/admin/support", adminResponseEnvelope, supportAdminRoutes);
router.use("/admin/payments", adminResponseEnvelope, paymentAdminRoutes);
router.use("/admin/subscriptions", adminResponseEnvelope, subscriptionAdminRoutes);
router.use("/admin/settings", adminResponseEnvelope, settingsAdminRoutes);

export default router;
